---
defaultGroups:
    - users
    - sudo
    - video
    - audio
    - dialout
    - plugdev
    - realtime
    - usrp
    - netdev
    - wireshark
    - docker
    - kvm

autologinGroup: autologin

doAutologin: false

sudoersGroup: sudo

setRootPassword: true

doReusePassword: true

passwordRequirements:
    minLength: 6

userShell: /bin/bash

defaultUserName: telcosec
allowWeakPasswords: false
